apiVersion: v1
kind: PersistentVolume
metadata:
        name: pets-pv
        labels:
                type: local
spec:
        storageClassName: pets-data
        capacity:
                storage: 30Gi
        accessModes:
           - ReadWriteOnce
        hostPath:
                path: "/pets_data"
